### ISSUE TITLE
Reflection doesn't work

### ISSUE THREAD

**Issue by ybigus** [jeromeetienne/threex.cubecamera#2]
On my local this demo shows black spheres. http://jeromeetienne.github.io/threex.cubecamera/examples/demo.html
Works well on my friend's PC. I am using Chrome (Версія 40.0.2214.94 m). In console I see errors: [.WebGLRenderingContext]GL ERROR :GL_OUT_OF_MEMORY : glGenerateMipmap: <- error from previous GL command. Update: works in FF...

**Comment by jeromeetienne** [comment]
out of memory seems related to your specific system. no ?

**Comment by ybigus** [comment]
Looks like. Following examples doesn't work in Chrome(but works in FireFox): examples/basic.html examples/demo.html, http://stemkoski.github.io/Three.js/Reflection.html. But examples/discoball.html works in Chrome well. I am using Windows 7, Chrome. Inter Core i5-2320, 8GB RAM, nvidia geforce 8800 gt. I'll try update drivers. I think for now make sense close this issue...
